/** @type {import('tailwindcss').Config} */
// Theme tokens ported verbatim from design/allthecode.md (Material-3 green theme).
module.exports = {
  // build.py renders HTML into dist/ BEFORE tailwind runs, so we purge against
  // the real output. Templates + calc.js are scanned too (calc.js toggles classes).
  content: [
    "./dist/**/*.html",
    "./src/templates/**/*.html",
    "./src/assets/calc.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#6f7a72",
        "on-error-container": "#93000a",
        "primary-container": "#006241",
        background: "#e6fff6",
        "surface-container-low": "#dbfaf0",
        "on-secondary-fixed-variant": "#384a46",
        "on-secondary": "#ffffff",
        "surface-container-high": "#d0efe4",
        "tertiary-fixed": "#ffdad7",
        "surface-container": "#d6f5ea",
        "on-background": "#04201a",
        "on-tertiary-fixed": "#3d0608",
        "surface-container-highest": "#cbe9df",
        "surface-bright": "#e6fff6",
        "primary-fixed": "#a2f3c8",
        secondary: "#4f625d",
        "on-secondary-fixed": "#0c1f1b",
        "surface-dim": "#c2e1d6",
        "outline-variant": "#bec9c0",
        "error-container": "#ffdad6",
        surface: "#e6fff6",
        "on-surface": "#04201a",
        "on-secondary-container": "#556863",
        "inverse-primary": "#87d7ad",
        "on-tertiary-fixed-variant": "#76312f",
        "tertiary-container": "#883f3c",
        "on-primary-fixed": "#002113",
        "secondary-fixed": "#d2e7e0",
        "inverse-on-surface": "#d9f7ed",
        "surface-tint": "#146b4a",
        "on-tertiary": "#ffffff",
        primary: "#00482f",
        "primary-fixed-dim": "#87d7ad",
        tertiary: "#6b2927",
        "on-primary-container": "#8bdbb1",
        "on-primary-fixed-variant": "#005235",
        "tertiary-fixed-dim": "#ffb3ae",
        "on-surface-variant": "#3f4943",
        "on-tertiary-container": "#ffb9b4",
        white: "#FFFFFF",
        "inverse-surface": "#1a352e",
        error: "#ba1a1a",
        "surface-variant": "#cbe9df",
        "secondary-container": "#d2e7e0",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b6cbc4",
        "on-error": "#ffffff",
        "accent-cream": "#F2F0EB",
        "on-primary": "#ffffff",
        "warm-gray": "#808080",
        "success-green": "#00754A",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        gutter: "24px",
        unit: "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        caption: ['"Source Sans 3"', "system-ui", "sans-serif"],
        "label-md": ['"Source Sans 3"', "system-ui", "sans-serif"],
        "display-lg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "body-lg": ['"Source Sans 3"', "system-ui", "sans-serif"],
        "body-md": ['"Source Sans 3"', "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  // Classes toggled at runtime by calc.js / progressive enhancement — keep them
  // even if a scanner misses the dynamic string concatenation.
  safelist: [
    "border-2", "border-primary", "border", "border-outline-variant",
    "bg-primary-fixed-dim", "text-on-primary-fixed", "bg-surface-container-lowest",
    "ring-2", "ring-primary-container", "hidden", "text-error",
  ],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
