"""
fetch_fonts.py — vendor Google Fonts locally so the site serves them same-origin.

Why: the live build linked two cross-origin Google Fonts stylesheets in <head>.
Those are render-blocking (Lighthouse: ~3.25 s) because the browser must open a
second connection (fonts.googleapis.com), download CSS, then a third
(fonts.gstatic.com) for the woff2 — all before first paint. The Material Symbols
icon font alone was 313 KiB. Self-hosting removes the cross-origin chain, and
subsetting the icon font to only the glyphs we use shrinks it by ~98 %.

This script is run ONCE by a maintainer (network needed); the resulting
src/assets/fonts/*.woff2 + the generated @font-face block in src/assets/app.css
are committed and copied into the image at build time (no network in Docker).

Run:  python scripts/fetch_fonts.py
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "src" / "assets" / "fonts"
APP_CSS = ROOT / "src" / "assets" / "app.css"

# A modern Chrome UA makes Google Fonts serve woff2 (smallest, universally supported).
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# Only keep western subsets — drink names use accents (Caffè, Crème) so we need
# latin-ext too, but we drop greek/cyrillic/vietnamese the site never renders.
KEEP_SUBSETS = {"latin", "latin-ext"}

# Every Material Symbol referenced in templates/CSS (keep this in sync with markup).
ICONS = sorted([
    "ac_unit", "arrow_forward", "bakery_dining", "bolt", "calculate",
    "chevron_right", "coffee", "cookie", "database", "expand_more", "icecream",
    "local_bar", "local_cafe", "lunch_dining", "menu_book", "nutrition",
    "search", "touch_app", "tune", "verified",
])

ICON_NAMES = ",".join(ICONS)

FAMILIES = [
    {
        "key": "plus-jakarta-sans",
        "css": "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap",
        "display": "swap",
    },
    {
        "key": "source-sans-3",
        "css": "https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600&display=swap",
        "display": "swap",
    },
    {
        "key": "material-symbols-outlined",
        "css": ("https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
                f":opsz,wght,FILL,GRAD@24,400,0,0&icon_names={ICON_NAMES}&display=block"),
        "display": "block",
    },
]

MARKER_START = "/* === VENDORED @font-face (generated by scripts/fetch_fonts.py) === */"
MARKER_END = "/* === end vendored @font-face === */"

# Optional "/* subset */" comment (icon font omits it), then the @font-face body.
BLOCK_RE = re.compile(r"(?:/\*\s*([\w-]+)\s*\*/\s*)?@font-face\s*{([^}]*)}", re.S)
PROP_RE = lambda name, css: (re.search(rf"{name}\s*:\s*([^;]+);", css) or [None, None])[1]
# Body fonts use ...woff2 URLs; the icon subset uses a /l/font?kit=... woff2 URL.
URL_RE = re.compile(r"url\((https://[^)]+)\)\s*format\(['\"]woff2['\"]\)")


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read().decode("utf-8")


def download(url: str, dst: Path):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        dst.write_bytes(r.read())


def main():
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    out_blocks: list[str] = []
    total_bytes = 0

    for fam in FAMILIES:
        css = fetch(fam["css"])
        seen_combo: dict[str, int] = {}
        for m in BLOCK_RE.finditer(css):
            subset, body = m.group(1), m.group(2)
            family = (PROP_RE("font-family", body) or "").strip().strip('"').strip("'")
            weight = (PROP_RE("font-weight", body) or "400").strip()
            style = (PROP_RE("font-style", body) or "normal").strip()
            urange = (PROP_RE("unicode-range", body) or "").strip()
            url_m = URL_RE.search(body)
            if not url_m:
                continue
            # Material Symbols subset has no named subset comment — keep all its blocks.
            is_icon = fam["key"] == "material-symbols-outlined"
            if not is_icon and subset not in KEEP_SUBSETS:
                continue

            tag = subset or "icons"
            n = seen_combo.get(f"{weight}-{tag}", 0)
            seen_combo[f"{weight}-{tag}"] = n + 1
            suffix = f"-{n}" if n else ""
            fname = f"{fam['key']}-{weight}-{tag}{suffix}.woff2"
            dst = FONTS_DIR / fname
            download(url_m.group(1), dst)
            total_bytes += dst.stat().st_size
            print(f"  {fname:48} {dst.stat().st_size/1024:6.1f} KiB")

            ur = f"\n  unicode-range: {urange};" if urange else ""
            out_blocks.append(
                f"@font-face {{\n"
                f"  font-family: '{family}';\n"
                f"  font-style: {style};\n"
                f"  font-weight: {weight};\n"
                f"  font-display: {fam['display']};\n"
                f"  src: url('fonts/{fname}') format('woff2');{ur}\n"
                f"}}"
            )

    block = MARKER_START + "\n" + "\n".join(out_blocks) + "\n" + MARKER_END

    text = APP_CSS.read_text(encoding="utf-8")
    if MARKER_START in text:
        text = re.sub(re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END),
                      block, text, flags=re.S)
    else:
        text = block + "\n\n" + text
    APP_CSS.write_text(text, encoding="utf-8")

    print(f"\nVendored {len(out_blocks)} faces, {total_bytes/1024:.1f} KiB total "
          f"-> {FONTS_DIR.relative_to(ROOT)}")
    print(f"Injected @font-face block into {APP_CSS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
